---
- hosts: jenkins
  become: yes
  gather_facts: true
  tasks:
    - name: Apt update & upgrade
      apt:
        update_cache: yes
        upgrade: yes
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: Install docker
      apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
    - name: Add ubuntu user to docker group
      shell: usermod -aG docker ubuntu
    - name: Clone cours_ynov repo
      git:
        clone: yes
        dest: cours_ynov
        repo: 'https://github.com/j0h3/cours_ynov.git'